using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wiki_Blaze.Migrations
{
    public partial class RemoveOwnerAttributeFromWikiProperties : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM [WikiPageAttributeValues] WHERE [AttributeDefinitionId] = 1;");

            migrationBuilder.DeleteData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "WikiAttributeDefinitions",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.UpdateData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 2,
                column: "SortOrder",
                value: 1);

            migrationBuilder.UpdateData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 3,
                column: "SortOrder",
                value: 2);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 2,
                column: "SortOrder",
                value: 2);

            migrationBuilder.UpdateData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 3,
                column: "SortOrder",
                value: 3);

            migrationBuilder.InsertData(
                table: "WikiAttributeDefinitions",
                columns: new[] { "Id", "Description", "IsAutoGenerated", "IsRequired", "Name", "ValueType" },
                values: new object[] { 1, "Verantwortliche Person", false, true, "Owner", "text" });

            migrationBuilder.InsertData(
                table: "WikiAttributeTemplateAttributes",
                columns: new[] { "Id", "AttributeDefinitionId", "IsRequired", "SortOrder", "TemplateId" },
                values: new object[] { 1, 1, true, 1, 1 });
        }
    }
}
