using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Wiki_Blaze.Migrations
{
    /// <inheritdoc />
    public partial class NewEigenschaftrefac : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Keep this as an incremental migration: remove the legacy "Owner" seed
            // and normalize template sort order. This allows clean DB creation
            // together with the preceding initial migration.
            migrationBuilder.DeleteData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.DeleteData(
                table: "WikiAttributeDefinitions",
                keyColumn: "Id",
                keyValue: 1);

            migrationBuilder.UpdateData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 2,
                column: "SortOrder",
                value: 1);

            migrationBuilder.UpdateData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 3,
                column: "SortOrder",
                value: 2);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "WikiAttributeDefinitions",
                columns: new[] { "Id", "Description", "IsAutoGenerated", "IsRequired", "Name", "ValueType" },
                values: new object[] { 1, "Verantwortliche Person", false, true, "Owner", "text" });

            migrationBuilder.UpdateData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 2,
                column: "SortOrder",
                value: 2);

            migrationBuilder.UpdateData(
                table: "WikiAttributeTemplateAttributes",
                keyColumn: "Id",
                keyValue: 3,
                column: "SortOrder",
                value: 3);

            migrationBuilder.InsertData(
                table: "WikiAttributeTemplateAttributes",
                columns: new[] { "Id", "AttributeDefinitionId", "IsRequired", "SortOrder", "TemplateId" },
                values: new object[] { 1, 1, true, 1, 1 });
        }
    }
}
