using System.ComponentModel.DataAnnotations;

namespace Wiki_Blaze.Data.Entities
{
    public class WikiAttributeDefinition
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MaxLength(100)]
        public string Name { get; set; } = string.Empty;

        [MaxLength(250)]
        public string? Description { get; set; }

        [MaxLength(50)]
        public string ValueType { get; set; } = "text";

        public bool IsRequired { get; set; }

        public bool IsAutoGenerated { get; set; }
    }
}
